linters:
  enable-all: true
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default
  disable:
    - maintidx
    - testpackage
    - nlreturn
    - gomnd
    - forcetypeassert
    - wsl
    - whitespace
    - prealloc
    - ineffassign
    - lll
    - funlen
    - dupl
    - gofumpt
    - gofmt
    - godot
    - gci
    - goimports
    - gocognit
    - gochecknoinits
    - goconst
    - depguard
    - nestif
    - ifshort
    - nosnakecase
    - scopelint
  # Enable presets.
  # https://golangci-lint.run/usage/linters
  # Run only fast linters from enabled linters set (first run won't be fast)
  # Default: false
  fast: true
